import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import '../styles/experience.css';

const EXPERIENCE = [
  {
    icon: 'fa-laptop-code',
    role: 'SDE Intern',
    date: 'Apr 2026 – Present',
    duration: '< 1 yr',
    company: 'Skypoint · Bangalore, India',
    stack: 'FastAPI · React · TypeScript · PostgreSQL · GCP (Speech-to-Text, Vertex AI) · FHIR R4 · Chrome Extension',
    points: [
      <>Working across three Skypoint products — <strong>Sky Command</strong>, <strong>SkyMDM</strong> and <strong>SkyCare</strong> — contributing to feature development and system improvements.</>,
      <><strong>Sky Command:</strong> collaborating with the engineering team to build <strong>scalable solutions</strong> and enhance overall platform performance.</>,
      <><strong>SkyMDM:</strong> contributing to <strong>feature development</strong> and product improvements on Skypoint's MDM platform alongside the engineering team.</>,
      <><strong>SkyCare:</strong> working on an <strong>AI medical scribe</strong> that records doctor–patient visits, transcribes the conversation, and generates structured <strong>SOAP notes</strong> written directly into the EHR (eClinicalWorks, NextGen).</>,
      <><strong>SkyCare · Backend:</strong> multi-tenant <strong>FastAPI + PostgreSQL</strong> services with a separate schema per clinic, <strong>Azure AD B2C</strong> login (JWT with PKCE), role-based access and audit logging of patient data access.</>,
      <><strong>SkyCare · AI pipeline:</strong> live audio streamed over <strong>WebSockets</strong> to Google Cloud Speech-to-Text, with notes generated by <strong>Gemini on Vertex AI</strong> against a strict JSON schema validated with Pydantic.</>,
      <><strong>SkyCare · Clinical grounding:</strong> diagnoses, medications and lab tests matched to <strong>ICD-10, RxNorm and LOINC</strong> using pgvector fuzzy search, flagging low-confidence matches for the doctor instead of guessing.</>,
      <><strong>SkyCare · Frontend:</strong> <strong>React + TypeScript</strong> web app (Vite, React Query) with record, live-transcript and note-review screens, capturing the microphone through the Web Audio API and reconnecting automatically if the network drops.</>,
      <><strong>SkyCare · Chrome extension:</strong> the same React app packaged as a <strong>Manifest V3</strong> extension that opens in a <strong>side panel</strong> beside the patient chart, with a background service worker, content script and a fixed extension id so login redirects keep working.</>,
      <><strong>SkyCare · Extension audio:</strong> microphone capture moved into an <strong>offscreen document</strong>, with typed messaging between the side panel, service worker and offscreen page so recording continues when the doctor switches tabs.</>,
      <><strong>SkyCare · EHR page integration:</strong> a <strong>content script</strong> detects the open eClinicalWorks chart, reads the patient's name, date of birth and EHR id to auto-select the right patient, and fills note sections into the chart where FHIR isn't supported.</>,
      <><strong>SkyCare · EHR write-back:</strong> notes written via <strong>FHIR R4</strong> (eClinicalWorks) and SQL (NextGen) with patient-match checks, retry-safe writes and per-section write logs, built with <strong>HIPAA</strong> safeguards in mind.</>,
    ],
  },
  {
    icon: 'fa-paint-brush',
    role: 'UI/UX Intern',
    date: 'Jun 2025 – Aug 2025',
    duration: '3 months',
    company: 'Confiable Technocraft · Remote',
    stack: 'UI/UX Design · Responsive Web · Chatbot Integration · Performance Optimization',
    points: [
      <>Developed a <strong>responsive website</strong> with modern UI/UX principles and interactive elements for the client.</>,
      <>Integrated a <strong>chatbot</strong> into the platform and optimized overall site performance for a seamless user experience.</>,
    ],
  },
  {
    icon: 'fa-brain',
    role: 'Machine Learning Intern',
    date: 'May 2024 – Jul 2024',
    duration: '3 months',
    company: 'National Institute of Technology Rourkela · Rourkela, India',
    stack: 'Python · Deep Learning · UNet · Squeeze-and-Excitation · ASPP · PyTorch',
    points: [
      <>Led the <strong>Automated Nucleus Segmentation</strong> project, engineering a deep learning model leveraging enhanced UNet architecture with <strong>Squeeze-and-Excitation (SE) blocks</strong> and <strong>ASPP</strong>.</>,
      <>Implemented advanced loss functions — <strong>Jaccard Distance, Dice Loss, Focal Loss</strong> — effectively mitigating class imbalances in histopathological datasets.</>,
      <>Achieved strong metrics: <strong>F1 Score: 0.7613</strong>, <strong>Accuracy: 90.80%</strong>, and <strong>Dice Coefficient: 0.6357</strong>.</>,
    ],
  },
];

const PREVIEW_COUNT = 1;

export default function Experience() {
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    if (!selected) return;
    const close = () => setSelected(null);
    window.addEventListener('hashchange', close);
    return () => window.removeEventListener('hashchange', close);
  }, [selected]);

  return (
    <section id="experience">
      <div className="container">
        <p className="section-label reveal">// work experience</p>
        <h2 className="section-title reveal">Where I've Worked</h2>
        <div className="section-line reveal" />
        <div className="timeline">
          {EXPERIENCE.map((exp, i) => (
            <div className="timeline-item reveal" key={i}>
              <div className="timeline-dot"><i className={`fas ${exp.icon}`} /></div>
              <div className="timeline-card">
                <div className="exp-header">
                  <div className="exp-role">{exp.role}</div>
                  <div className="exp-date">
                    {exp.date}
                    {exp.duration && <span className="exp-duration">{exp.duration}</span>}
                  </div>
                </div>
                <div className="exp-company">{exp.company}</div>
                {exp.stack && <div className="exp-stack">{exp.stack}</div>}
                <ul className="exp-points">
                  {exp.points.slice(0, PREVIEW_COUNT).map((pt, j) => <li key={j}>{pt}</li>)}
                </ul>
                {exp.points.length > PREVIEW_COUNT && (
                  <div className="exp-view-more-wrap">
                    <button className="exp-view-more" onClick={() => setSelected(exp)}>
                      <i className="fas fa-plus-circle" /> View More
                      <span className="exp-count">+{exp.points.length - PREVIEW_COUNT} more</span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      {selected && createPortal(
        <div className="exp-modal-backdrop" onClick={() => setSelected(null)}>
          <div className={`exp-modal${selected.points.length > 6 ? ' exp-modal--wide' : ''}`} onClick={e => e.stopPropagation()}>
            <button className="exp-modal-close" onClick={() => setSelected(null)}>
              <i className="fas fa-times" />
            </button>
            <div className="exp-modal-header">
              <div className="exp-modal-dot"><i className={`fas ${selected.icon}`} /></div>
              <div>
                <div className="exp-modal-role">{selected.role}</div>
                <div className="exp-modal-company">{selected.company}</div>
                <div className="exp-modal-date">
                  {selected.date}
                  {selected.duration && <span className="exp-duration">{selected.duration}</span>}
                </div>
              </div>
            </div>
            {selected.stack && <div className="exp-stack exp-modal-stack">{selected.stack}</div>}
            <ul className="exp-modal-points">
              {selected.points.map((pt, j) => <li key={j}>{pt}</li>)}
            </ul>
          </div>
        </div>,
        document.body
      )}
    </section>
  );
}
